version: '3.9' 

services:

  client:
    build:
      context: client
    ports:
      - 3000:3000
    volumes:
      - ./client/public:/client/public
      - node_modules_client:/client/node_modules

  backend:
    build:
      context: server
    ports:
      - 5000:5000
    volumes:
      - ./server:/backend
      - ./client/public:/client/public
      - node_modules_backend:/backend/node_modules 

volumes:
  node_modules_client:
  node_modules_backend: